title: Cheat sheets corpus
description: A compilation of cheat sheets found throughout the internet.
theme: just-the-docs

url: https://script-multiplexer.github.io/cheat-sheets-corpus/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Color scheme supports "light" (default) or "dark"
color_scheme: dark